changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: ✨ New features
      labels:
        - enhancement
        - feature
    - title: 🐛 Fixes
      labels:
        - bug
        - fix
    - title: 🎨 UI & UX
      labels:
        - ui
        - ux
    - title: 🌐 Localization
      labels:
        - localization
        - i18n
    - title: 🧰 Maintenance
      labels:
        - maintenance
        - dependencies
        - ci
    - title: Other changes
      labels:
        - '*'
